steps:
# Bước 1: Build Docker image từ Dockerfile của bạn
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'asia-southeast1-docker.pkg.dev/sviuh-startup-lab/cloud-run/frontend-node:$COMMIT_SHA' # Thay thế bằng đường dẫn Artifact Registry của bạn
  - '-f'
  - 'Dockerfile' # Đảm bảo Dockerfile nằm ở thư mục gốc hoặc chỉ định đường dẫn chính xác
  - '.'

# Bước 2: Push Docker image lên Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'asia-southeast1-docker.pkg.dev/sviuh-startup-lab/cloud-run/frontend-node:$COMMIT_SHA' # Thay thế bằng đường dẫn Artifact Registry của bạn

# Bước 3: Triển khai ảnh container lên Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'startup-lab-web' # Tên dịch vụ Cloud Run của bạn
  - '--image'
  - 'asia-southeast1-docker.pkg.dev/sviuh-startup-lab/cloud-run/frontend-node:$COMMIT_SHA' # Đường dẫn ảnh đã push
  - '--region'
  - 'asia-southeast1' # Khu vực Cloud Run của bạn
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # Hoặc cấu hình xác thực phù hợp với bạn
  # Thêm các tham số cấu hình khác cho Cloud Run nếu cần, ví dụ:
  # - '--cpu=1'
  # - '--memory=512Mi'
  # - '--min-instances=0'
  # - '--max-instances=2'
  # - '--set-env-vars=NODE_ENV=production'

images:
- 'asia-southeast1-docker.pkg.dev/sviuh-startup-lab/cloud-run/frontend-node:$COMMIT_SHA' # Đường dẫn ảnh đã push
