// app/templates/sectionMap.ts
import { AboutSection, AIFeaturesSection, APIEndpointsSection, ApplicationProcessSection, BenefitsSection, BuyerBenefitsSection, CategoriesSection, CompanyCultureSection, ComplianceSection, ContactSection, ContentManagementSection, CoursesSection, CTASection, DashboardOverviewSection, DashboardSection, DemoSection, DocsSection, EducationSection, EmployeeTestimonialsSection, ExperienceSection, FeaturesSection, GallerySection, GoalsSection, HeroSection, HighlightsSection, IntegrationSection, LearningPathSection, ListingsSection, PositionsSection, ProductsSection, ProjectsSection, PublicationsSection, ResearchAreasSection, SellerBenefitsSection, ServicesSection, SkillsSection, StatsSection, StrengthsSection, StudentProjectsSection, SummarySection, SystemSettingsSection, UseCasesSection, UserManagementSection } from "./sections";

export const sectionMap: { [key: string]: React.FC<any> } = {
  hero: HeroSection,
  features: FeaturesSection,
  products: ProductsSection,
  contact: ContactSection,
  stats: StatsSection,
  dashboard: DashboardSection,
  cta: CTASection,
  benefits: BenefitsSection,
  about: AboutSection,
  services: ServicesSection,
  dashboardOverview: DashboardOverviewSection,
  userManagement: UserManagementSection,
  contentManagement: ContentManagementSection,
  systemSettings: SystemSettingsSection,
  courses: CoursesSection,
  learningPath: LearningPathSection,
  studentProjects: StudentProjectsSection,
  projects: ProjectsSection,
  skills: SkillsSection,
  categories: CategoriesSection,
  listings: ListingsSection,
  sellerBenefits: SellerBenefitsSection,
  buyerBenefits: BuyerBenefitsSection,
  aiFeatures: AIFeaturesSection,
  useCases: UseCasesSection,
  demo: DemoSection,
  docs: DocsSection,
  apiEndpoints: APIEndpointsSection,
  integration: IntegrationSection,
  compliance: ComplianceSection,
  researchAreas: ResearchAreasSection,
  publications: PublicationsSection,
  highlights: HighlightsSection,
  gallery: GallerySection,
  summary: SummarySection,
  experience: ExperienceSection,
  education: EducationSection,
  strengths: StrengthsSection,
  goals: GoalsSection,
  positions: PositionsSection,
  applicationProcess: ApplicationProcessSection,
  companyCulture: CompanyCultureSection,
  employeeTestimonials: EmployeeTestimonialsSection,
};
